"""Read Unity assets; export relevant atlases and untrimmed PNG sprites."""
from pathlib import Path
import hashlib
import json
import re
import UnityPy
from PIL import Image

OUT = Path(__file__).parent
GAME = Path(r'C:\Users\bjise\Downloads\site\RWLD_copy')
SOURCE = GAME / 'RainWorld_Data/resources.assets'
env = UnityPy.load(str(SOURCE))
literal_sources = {}
for group in ('render', 'holograms', 'optional'):
    for file in (OUT / 'code' / group).glob('*.cs'):
        for literal in re.findall(r'"([^"\r\n]+)"', file.read_text(encoding='utf-8')):
            literal_sources.setdefault(literal, set()).add(file.relative_to(OUT).as_posix())
atlas_names = {'rainWorld', 'uiSprites', 'rainworldmsc', 'uispritesmsc'}
for obj in env.objects:
    if obj.type.name != 'TextAsset':
        continue
    data = obj.read()
    try:
        candidate = json.loads(data.m_Script)
    except (ValueError, TypeError):
        continue
    if isinstance(candidate, dict) and any(Path(k).stem in literal_sources for k in candidate.get('frames', {})):
        atlas_names.add(data.m_Name)
textures, maps, provenance = {}, {}, []
for obj in env.objects:
    if obj.type.name not in ('Texture2D', 'TextAsset'):
        continue
    data = obj.read()
    if data.m_Name not in atlas_names:
        continue
    directory = OUT / 'atlases'
    directory.mkdir(exist_ok=True)
    if obj.type.name == 'Texture2D':
        textures[data.m_Name] = data.image.convert('RGBA')
        dest = directory / (data.m_Name + '.png')
        textures[data.m_Name].save(dest)
    else:
        raw = data.m_Script
        if isinstance(raw, bytes):
            raw = raw.decode('utf-8')
        maps[data.m_Name] = json.loads(raw)
        dest = directory / (data.m_Name + '.json')
        dest.write_text(raw, encoding='utf-8')
    provenance.append({'source': str(SOURCE), 'path_id': obj.path_id, 'type': obj.type.name,
                       'name': data.m_Name, 'output': dest.relative_to(OUT).as_posix()})

literal_sources = {}
for group in ('render', 'holograms', 'optional'):
    for file in (OUT / 'code' / group).glob('*.cs'):
        for literal in re.findall(r'"([^"\r\n]+)"', file.read_text(encoding='utf-8')):
            literal_sources.setdefault(literal, set()).add(file.relative_to(OUT).as_posix())

sprites = []
for name, metadata in maps.items():
    image = textures[name]
    for key, frame in metadata['frames'].items():
        stem = Path(key).stem
        # Tutorial constructs key/button symbols dynamically.
        dynamic = stem.startswith(('key', 'button'))
        if stem not in literal_sources and not dynamic:
            continue
        assert not frame['rotated'], (name, key, 'rotated atlas frame')
        f = frame['frame']
        box = (f['x'], f['y'], f['x'] + f['w'], f['y'] + f['h'])
        assert 0 <= box[0] < box[2] <= image.width and 0 <= box[1] < box[3] <= image.height
        cropped = image.crop(box)
        size, offset = frame['sourceSize'], frame['spriteSourceSize']
        result = Image.new('RGBA', (size['w'], size['h']))
        result.paste(cropped, (offset['x'], offset['y']))
        folder = OUT / 'sprites' / name
        folder.mkdir(parents=True, exist_ok=True)
        dest = folder / (stem + '.png')
        result.save(dest)
        sprites.append({'name': stem, 'atlas': name, 'output': dest.relative_to(OUT).as_posix(),
                        'selection': 'literal' if stem in literal_sources else 'dynamic tutorial key/button family',
                        'references': sorted(literal_sources.get(stem, set())), 'original_frame': frame})

# This texture is generated by Futile.CreateDefaultAtlases, not stored in an atlas.
generated = OUT / 'textures/Futile_White.png'
Image.new('RGBA', (16, 16), (255, 255, 255, 255)).save(generated)
provenance.append({'source': 'Futile.CreateDefaultAtlases()', 'output': 'textures/Futile_White.png',
                   'kind': 'recreated runtime texture', 'size': [16, 16], 'filter': 'Bilinear', 'wrap': 'Clamp'})

found = {x['name'] for x in sprites}
required = {'Circle20', 'pixel', 'Circle4', 'mouseEyeA1', 'mouseEyeB1', 'LizardBubble0',
            'GuidanceEnergyCell', 'GuidanceMoon', 'GuidanceNeuron', 'GuidancePebbles',
            'GuidanceSlugcat', 'batSymbol', 'foodSymbol', 'shelterSymbol', 'miscDangerSymbol', 'spearSymbol'}
missing = sorted(required - found)
assert not missing, missing
optional = set()
for file in (OUT / 'code/holograms').glob('*.cs'):
    optional.update(re.findall(r'new Layer\("([^"]+)"', file.read_text(encoding='utf-8')))
(OUT / 'unresolved-assets.json').write_text(json.dumps({
    'required_core_missing': missing,
    'optional_GateScene_missing': sorted(optional - found),
    'note': 'GateScene names were not found in scanned Unity assets or loose filenames. No substitutes generated.'
}, indent=2), encoding='utf-8')
(OUT / 'sprites.json').write_text(json.dumps(sprites, ensure_ascii=False, indent=2), encoding='utf-8')
(OUT / 'extracted-assets.json').write_text(json.dumps(provenance, indent=2), encoding='utf-8')
print(f'Exported {len(textures)} atlases, {len(sprites)} sprites; required sprites verified.')
